In [10]:
from facenet_pytorch import MTCNN, InceptionResnetV1
import torch
import torchvision.transforms as T
from PIL import Image

import os

In [11]:
images_path = 'data/full_images'
faces_path = 'data/faces'

In [12]:
# Create face detection pipeline to get face samples from bigger images
mtcnn = MTCNN()

# Create an inception resnet (in eval mode):
resnet = InceptionResnetV1(pretrained='vggface2').eval()

In [13]:
# Take all the images and cut the face
for image_name in os.listdir(images_path):
    img = Image.open(os.path.join(images_path,image_name))
    # Get cropped image tensor
    img_cropped = mtcnn(img, save_path=os.path.join(faces_path,image_name))

In [14]:
# Take sample image and calculate embeddings
cos_sim = torch.nn.CosineSimilarity()
sample_img = Image.open(os.path.join(faces_path,os.listdir(faces_path)[8]))
convert_tensor = T.ToTensor()
emb_sample = resnet(convert_tensor(sample_img).unsqueeze(0))

In [15]:
#Measure similarities and distance against the sample image
for image_name in os.listdir(faces_path):
    
    img = Image.open(os.path.join(faces_path,image_name))
    img_embedding = resnet(convert_tensor(img).unsqueeze(0))
    
    # Calculate similarity
    sim = cos_sim(emb_sample,img_embedding)
    dist = (emb_sample - img_embedding).norm()
    print(sim)
    print(dist)

tensor([0.6042], grad_fn=<SumBackward1>)
tensor(0.8897, grad_fn=<CopyBackwards>)

tensor([0.6206], grad_fn=<SumBackward1>)
tensor(0.8711, grad_fn=<CopyBackwards>)

tensor([0.6797], grad_fn=<SumBackward1>)
tensor(0.8004, grad_fn=<CopyBackwards>)

tensor([0.9138], grad_fn=<SumBackward1>)
tensor(0.4153, grad_fn=<CopyBackwards>)

tensor([0.9079], grad_fn=<SumBackward1>)
tensor(0.4292, grad_fn=<CopyBackwards>)

tensor([0.6400], grad_fn=<SumBackward1>)
tensor(0.8485, grad_fn=<CopyBackwards>)

tensor([0.8032], grad_fn=<SumBackward1>)
tensor(0.6274, grad_fn=<CopyBackwards>)

tensor([0.8133], grad_fn=<SumBackward1>)
tensor(0.6111, grad_fn=<CopyBackwards>)

tensor([1.0000], grad_fn=<SumBackward1>)
tensor(0., grad_fn=<CopyBackwards>)

tensor([0.6135], grad_fn=<SumBackward1>)
tensor(0.8792, grad_fn=<CopyBackwards>)

